In [1]:
#1.kutuphaneler
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#2.1 veri yukleme
veri = pd.read_csv('veriler.csv')
boy = veri[['boy']],
print(boy)
boykilo = veri[['boy','kilo']]
print(boykilo)


    boy
0   130
1   125
2   135
3   133
4   129
5   180
6   190
7   175
8   177
9   185
10  165
11  155
12  160
13  162
14  167
15  174
16  193
17  187
18  183
19  159
20  164
21  166
    boy  kilo
0   130    30
1   125    36
2   135    34
3   133    30
4   129    38
5   180    90
6   190    80
7   175    90
8   177    60
9   185   105
10  165    55
11  155    50
12  160    58
13  162    59
14  167    62
15  174    70
16  193    90
17  187    80
18  183    88
19  159    40
20  164    66
21  166    56


In [29]:
from sklearn.impute import SimpleImputer
imputer= SimpleImputer(missing_values=np.nan,strategy="mean")
veriler_eksik = pd.read_csv('veriler_eksik.csv')
#print(veriler_eksik)
#mean ortalama almak ve nan olan yerlere yerlestirmek

#----------------------------------------------------------------

#2.veri onisleme
uc_kolon=veriler_eksik.iloc[:,1:4].values
print(uc_kolon)#dizi sekline cevrilmis 3 kolon


imputer = imputer.fit(uc_kolon[:,1:4])
uc_kolon[:,1:4] = imputer.transform(uc_kolon[:,1:4])
print(uc_kolon)# ortalma hesaplanip datadaki nan bosluklar dolduruldu

[[130.  30.  10.]
 [125.  36.  11.]
 [135.  34.  10.]
 [133.  30.   9.]
 [129.  38.  12.]
 [180.  90.  30.]
 [190.  80.  25.]
 [175.  90.  35.]
 [177.  60.  22.]
 [185.  nan  33.]
 [165.  55.  27.]
 [155.  50.  44.]
 [160.  58.  39.]
 [162.  nan  41.]
 [167.  62.  55.]
 [174.  nan  47.]
 [193.  90.  23.]
 [187.  80.  27.]
 [183.  88.  28.]
 [159.  40.  29.]
 [164.  66.  32.]
 [166.  56.  42.]]
[[130.          30.          10.        ]
 [125.          36.          11.        ]
 [135.          34.          10.        ]
 [133.          30.           9.        ]
 [129.          38.          12.        ]
 [180.          90.          30.        ]
 [190.          80.          25.        ]
 [175.          90.          35.        ]
 [177.          60.          22.        ]
 [185.          59.63157895  33.        ]
 [165.          55.          27.        ]
 [155.          50.          44.        ]
 [160.          58.          39.        ]
 [162.          59.63157895  41.        ]
 [167.         

In [35]:
#Categoric Data
veriler = pd.read_csv('veriler.csv')

Yas = veriler.iloc[:,1:4].values# nunmy arraylerine ceviriyoruz
#print(Yas)

ulke = veriler.iloc[:,0:1].values
#print(ulke)

from sklearn import preprocessing
le = preprocessing.LabelEncoder()
ulke[:,0] = le.fit_transform(veriler.iloc[:,0])
print(ulke)# 11122233 seklinde sayiya ceviriyor

ohe = preprocessing.OneHotEncoder()
ulke = ohe.fit_transform(ulke).toarray()
print(ulke)# [0. 1. 0.] [1. 0. 0.] seklinde sayiya ceviriyor

print(len(veriler.values)) #range bulduk
sonuc = pd.DataFrame(data=ulke, index = range(22), columns = ['fr','tr','us'])
#print(sonuc)#pandas veri tipine cevirdik exel dosyasi gibi uc baslikli



[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
22


Create Data Frame and Merge

In [19]:
sonuc2 = pd.DataFrame(data=Yas, index = range(22), columns = ['boy','kilo','yas'])
#print(sonuc2) # 1,2,3 indexli 22 ye kadar olan boy ve kilo , yas olan pandas datasi

cinsiyet = veriler.iloc[:,-1].values#create/
#print(cinsiyet)# cinsiyet numpay arrayi yaptik
sonuc3 = pd.DataFrame(data = cinsiyet, index = range(22), columns = ['cinsiyet'])
#print(sonuc3)# cinsiyet pandasi yaptik

s=pd.concat([sonuc,sonuc2], axis=1)
#print(s)

s2=pd.concat([s,sonuc3], axis=1)
print(s2)
# Butun Birlesimlerimizi yaptik.

     fr   tr   us  boy  kilo  yas cinsiyet
0   0.0  1.0  0.0  130    30   10        e
1   0.0  1.0  0.0  125    36   11        e
2   0.0  1.0  0.0  135    34   10        k
3   0.0  1.0  0.0  133    30    9        k
4   0.0  1.0  0.0  129    38   12        e
5   0.0  1.0  0.0  180    90   30        e
6   0.0  1.0  0.0  190    80   25        e
7   0.0  1.0  0.0  175    90   35        e
8   0.0  1.0  0.0  177    60   22        k
9   0.0  0.0  1.0  185   105   33        e
10  0.0  0.0  1.0  165    55   27        k
11  0.0  0.0  1.0  155    50   44        k
12  0.0  0.0  1.0  160    58   39        k
13  0.0  0.0  1.0  162    59   41        k
14  0.0  0.0  1.0  167    62   55        k
15  1.0  0.0  0.0  174    70   47        e
16  1.0  0.0  0.0  193    90   23        e
17  1.0  0.0  0.0  187    80   27        e
18  1.0  0.0  0.0  183    88   28        e
19  1.0  0.0  0.0  159    40   29        k
20  1.0  0.0  0.0  164    66   32        k
21  1.0  0.0  0.0  166    56   42        k
